@birthday = 1978-07-28

### Calculate age from date
POST {{host}}/api/calculate-age
Accept: application/json
Content-Type: application/json;charset=UTF-8

{
  "query": "The date is {{birthday}}"
}

?? status == 200
?? header content-type includes json
?? body output startsWith Your age is
?? body output matches \d+ years?, \d+ months?, and \d+ days?\.$
