@query = Europe

### Get Bing Search URL

POST {{host}}/api/bing
Content-Type: application/json;charset=UTF-8

{
  "query": "Query: {{query}}"
}

?? status == 200
?? header content-type includes json
?? body length >= 5
?? body at(0) startsWith system:
?? body at(1) startsWith user:
?? body at(1) includes {{query}}
?? body at(2) equals assistant: null
?? body at(3) startsWith tool: 
?? body at(3) includes https://www.bing.com/search?q=
?? body at(3) includes {{query}}
?? body at(4) startsWith assistant: The URL for the search query
?? body at(4) includes {{query}}
?? body at(4) includes on Bing is:
?? body at(4) includes https://www.bing.com/search?q=
