@query = Europe

### Get Wikipedia URL

POST {{host}}/api/search-wiki
Content-Type: application/json;charset=UTF-8

{
  "query": "Query: {{query}}"
}

?? status == 200
?? header content-type includes json
